spring.application.name=cart-service
server.port=8083
jwts.security=JE3pjQYJ6/+hrQO0zo/6dydd9p7Xez+aZYfXfbLgm+U=

spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/cart
spring.datasource.username=postgres
spring.datasource.password=postgres30082004

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true